### ISSUE TITLE
Release a proper version

### ISSUE THREAD

**Issue by phaza** [geo-io/wkb-parser#1]
Hey,

I'm using wkb-parser (and wkb-interface) in a project of mine.
So far it's been working great, but since you haven't released a proper version, I have to set minimum-stability to dev in my composer.json in all my projects where I want to use my own package.

Any chance you can release a proper stable release? Your test coverage is great, and I've not had any major issues so far.

**Comment by jsor** [comment]
Version 1.0.0 tagged.

**Comment by phaza** [comment]
Thank you very much
