### ISSUE TITLE
Deprecated Warning on PHP 8.1.0

### ISSUE THREAD

**Issue by nison-jp** [geo-io/wkb-parser#4]
```
PHP Deprecated:  Implicit conversion from float 0.001 to int loses precision in /work/backend/vendor/geo-io/wkb-parser/src/Parser.php on line 74
PHP Deprecated:  Implicit conversion from float 0.001 to int loses precision in /work/backend/vendor/geo-io/wkb-parser/src/Parser.php on line 79
```
Using geo-io/wkb-parser v1.0.1, required by  [mstaack/laravel-postgis](https://github.com/mstaack/laravel-postgis), on PHP 8.1.0.

**Comment by jsor** [comment]
Thanks for the report. Fixed and released in [v1.0.2](https://github.com/geo-io/wkb-parser/releases/tag/v1.0.2).
