### ISSUE TITLE
Error when parsing empty GeometryCollection

### ISSUE THREAD

**Issue by rainerholzapfel** [geo-io/wkb-parser#5]
Hi, I'm trying to parse an empty geometery collection from a mysql db.

$parser->parse('00000000010700000000000000');

but it throws a ParserException: Parsing failed: Not enough bytes left to fulfill 1 double.

**Comment by jsor** [comment]
The internal format of MySQL is not identical to WKB, see https://dev.mysql.com/doc/refman/8.0/en/gis-data-formats.html

To be able to be parsed, you need to explicitly select the column as WKB, e.g.

```sql
SELECT ST_AsWKB(geometry_column) AS geometry_column
```

**Comment by rainerholzapfel** [comment]
Sry for being little bit off-topic, but do you know a way, for doing the wkb transformation with PHP (instead of using ST_AsWKB), e.g. with unpack?

**Comment by jsor** [comment]
The docs state

> Internal format is like WKB but with an initial 4 bytes to indicate the SRID.

So, you could try to chop off the first 4 bytes before passing to the WKB parser.

**Comment by rainerholzapfel** [comment]
Thanks, that worked.
