### ISSUE TITLE
MySQL parse point data error: Bad endian byte value 230

### ISSUE THREAD

**Issue by wimski** [geo-io/wkb-parser#6]
### Project Info
* `geo-io/wkb-parser`: `v1.0.2`
* PHP `8.0.16`
* MySQL `8.0.28`

### Description
First I save some point data with the following query `ST_PointFromText(POINT(90 180), 4326)`. Why MySQL expects the latitude first and then the longitude is beyond me, because latitude represents a Y coordinate and longitude an X coordinate. I therefore would expect a point to be defined as `X Y`. But that seems to be the case, because otherwise MySQL throws an error, so I just roll with it.
Then I retrieve that (raw) data back from the database and pass it on to `GeoIO\WKB\Parser\Parser::parse`. This throws the following exception:
```
GeoIO\WKB\Parser\Exception\ParserException : Parsing failed: Bad endian byte value 230.
```

Any idea what I'm doing wrong and how I can fix this?

**Comment by jsor** [comment]
You cannot parse the raw data from MySQL as is, see #5.

**Comment by wimski** [comment]
Ah, so MySQL is just not supported due to their deviations from the spec? Might be useful to mention this in the README.

For future reference, I made MySQL work with the following code instead of using this package:
```php
/** @var array<string, float> $coordinates */
$coordinates = unpack('x4/clat/Llat/dlongitude/dlatitude', $value);
return new MyCustomPoint($coordinates['latitude'], $coordinates['longitude']);
```
Inspired by: https://stackoverflow.com/questions/37467050/convert-mysqls-point-to-text-in-php#comment96288309_42322503

**Comment by jsor** [comment]
Just for the record, MySQL is supported if you make it return WKB with

```sql
SELECT ST_AsWKB(geometry_column) AS geometry_column
```

**Comment by wimski** [comment]
Good to know, although it's more of hassle changing the way my framework retrieves data than changing the processing of the data itself.
